# Generated by Django 4.0 on 2021-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nint_users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
