# Generated by Django 3.2.9 on 2021-12-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.PositiveIntegerField(max_length=30)),
                ('typeOfGame', models.CharField(max_length=30)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('winner', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.PositiveIntegerField(default=12)),
                ('location', models.CharField(max_length=3)),
                ('alive', models.BooleanField()),
                ('queen', models.BooleanField()),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chippers.game')),
            ],
        ),
    ]
