# Generated by Django 3.2.9 on 2021-12-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chippers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.PositiveIntegerField(),
        ),
    ]
