# Generated by Django 4.0 on 2021-12-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chippers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.PositiveIntegerField(),
        ),
    ]
