# Generated by Django 4.0 on 2021-12-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nint_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nint_users.profile'),
        ),
    ]
